### ISSUE TITLE
bootstrap fails: required file './ABOUT-NLS' not found

### ISSUE THREAD

**Issue by vollkommenheit** [mirror/wget#15]
Got the fix from https://lists.freedesktop.org/archives/modemmanager-devel/2017-February/003946.html, by changing ./configure.ac as below:

-AM_INIT_AUTOMAKE([subdir-objects dist-lzip])
+AM_INIT_AUTOMAKE([subdir-objects dist-lzip foreign])

**Comment by NilsIrl** [comment]
Discussed on mailinglist: https://lists.gnu.org/archive/html/bug-wget/2021-04/msg00006.html
